### PR TITLE
test: use random free port to avoid collisions

### LINKED ISSUE #49: test: randomize ports
Port assignments should be randomized, rather than hard coded, to avoid test failures

### LINKED ISSUE #745: test: randomize ports

### PR DESCRIPTION
**Pull request by dignifiedquire**
Closes n0-computer/iroh#745

### CODE REVIEW

**Review by flub — CHANGES_REQUESTED** [review]
I don't think the `portpicker` crate is that good: it is inherently racy.

We can use the OS-provided mechanism of binding the provider to port `0` and use `Provider::listen_address` to configure the get side in tests.  No new dependencies needed.

**Comment by dignifiedquire** [comment]
My experience when using `0` for doing cross platform things have been very mixed and the result of instability on non linux platforms, so I am not fully convinced it is a good idea to use it :/

**Review by ramfox — APPROVED** [review]
lock file conflict?

**Comment by dignifiedquire** [comment]
@flub your solution is simpler, so going with that for now

**Review by flub — APPROVED** [review]

**Pull request merged**
